import org.jetbrains.intellij.platform.gradle.IntelliJPlatformType

plugins {
    id("java")
    id 'org.jetbrains.intellij.platform' version '2.5.0'
}

group = "de.kontext-e.jqassistant.plugin"
version = "1.3.3"

repositories {
    mavenCentral()

    intellijPlatform {
        defaultRepositories()
    }
}

dependencies {
    intellijPlatform {
        intellijIdeaCommunity '2025.1'
        bundledPlugin 'com.intellij.java'
    }
}

intellijPlatform {
    buildSearchableOptions = false

    pluginVerification {
        ides {
            ide IntelliJPlatformType.IntellijIdeaCommunity, "2025.1"
            recommended()
            select {
                it.sinceBuild = "233"
            }
        }
    }

    signing {
        certificateChain = System.getenv("CERTIFICATE_CHAIN")
        privateKey = System.getenv("PRIVATE_KEY")
        password = System.getenv("PRIVATE_KEY_PASSWORD")
    }

    publishing {
        token = System.getenv("PUBLISH_TOKEN")
    }
}

java {
    sourceCompatibility = "17"
    targetCompatibility = "17"
}
